version: 0.2

env:
  variables:
    S3_BUCKET: "cinetrack-app-frontend"
    CLOUDFRONT_DISTRIBUTION_ID: "E23WYKPFGKN4V4"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd frontend
      - npm ci

  build:
    commands:
      - echo "Building frontend..."
      - npm run build

  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync build s3://$S3_BUCKET/ --delete
      - echo "Creating CloudFront invalidation..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*" || echo "⚠️ Invalidation failed (non-critical)"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
